{
 "title": "Monitoreo de Usuarios - CRUD",
 "description": "Dashboard de monitoreo del sistema CRUD de usuarios con Prometheus y PostgreSQL",
 "tags": [
  "usuarios",
  "fastapi",
  "prometheus",
  "postgresql"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Métricas de Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total de Usuarios Registrados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "usuarios_creados_total" }
   ]
  },
  {
   "title": "Evolución de Usuarios Registrados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    { "expr": "usuarios_creados_total" }
   ]
  },
  { "title": "Analítica de PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Edad Promedio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(AVG(age), 1) AS value FROM users;"
    }
   ]
  },
  {
   "title": "Edad Mínima",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(age) AS value FROM users;"
    }
   ]
  },
  {
   "title": "Edad Máxima",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(age) AS value FROM users;"
    }
   ]
  },
  {
   "title": "Últimos Usuarios Registrados",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"ID\", name AS \"Nombre\", age AS \"Edad\" FROM users ORDER BY id DESC LIMIT 10;"
    }
   ]
  }
 ]
}